### ISSUE TITLE
[BUG]Agent Tool type as GitHub -Authentication type resets to default "Anonymous" when switching from "Manual/Token or Password" to "Integration" and back to "Manual"

### ISSUE THREAD

**Issue by liana-gif** [ProjectAlita/projectalita.github.io#534]
**Description:**
When a user saves the "Manual" authentication type as either "Token" or "Password" and then switches to "Integration" before reverting back to "Manual," the previously selected option is not retained and is instead reset to the default "Anonymous" type.

**Steps to Reproduce:**
1. Navigate to the authentication settings.
2. Select the "Manual" authentication type.
3. Choose "Token" or "Password" and save the settings.
4. Switch the authentication type to "Integration" and save the settings.
5. Return to the authentication type settings and switch back to "Manual".
6. Notice that the authentication type has been reset to "Anonymous" instead of retaining the previously saved "Token" or "Password" option.

**Actual Result:** 
The authentication type is reset to the default "Anonymous" option after switching back to "Manual".

**Expected Result:**
 The authentication type should retain the user's last saved selection ("Token" or "Password") after switching back to "Manual" from "Integration".
See attached demo

**Comment by HawkQing1** [comment]
@liana-gif, this not a bug, because once you select a configuration, then there will be only configuration information stored in DB, other details information, e.g. Authentication information, is related to the configuration. If you switch to "Manual", the initial default Authentication settings will be loaded.
By the way, please use the names from UI to describe the issue, or else I can only guess what your description. Thanks!
